version: "3.9"

services:
  etl:
    platform: "linux/amd64"
    # Build from your Dockerfile AND tag the image
    build:
      context: .
      dockerfile: Dockerfile
    image: ateet555/masx-ai-etl:v1

    ports:
      - "8000:8000"

    # Load variables from .env (for substitution) and also pass them into the container
    env_file: .env
    environment:
      # Safe defaults if .env is missing a key (fixes your int(None) crash)
      MAX_WORKERS: "${MAX_WORKERS:-4}"
      CHROMA_PERSIST_DIR: "${CHROMA_PERSIST_DIR:-/data/chroma}"
      CHROMA_HOST: "${CHROMA_HOST:-localhost}"
      CHROMA_PORT: "${CHROMA_PORT:-8001}"
      LOG_LEVEL: "${LOG_LEVEL:-info}"

    volumes:
      - masx_chroma:/data/chroma

    # Keep it alive across reboots
    restart: unless-stopped

    # Basic healthcheck (hits docs; swap to /healthz if you have one)
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/docs" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    # GPU (optional). Uncomment if you truly need CUDA in Compose.
    # device_requests:
    #   - driver: nvidia
    #     count: all
    #     capabilities: [gpu]

volumes:
  masx_chroma:
