mock_data = [
    {
        "url": "http://www.xinhuanet.com/politics/2020-12/31/c_1126934011.htm",
        "url_mobile": None,
        "title": "中印边界问题特别代表会晤取得6点共识",
        "seendate": "2024-12-18T00:00:00",
        "socialimage": "",
        "domain": "xinhuanet.com",
        "language": "Chinese",
        "sourcecountry": "CN",
    },
    {
        "url": "https://www.dw.com/en/india-china-border-dispute-can-the-peace-last/a-70712678",
        "url_mobile": None,
        "title": "India–China border dispute: Can the peace last?",
        "seendate": "2025-06-15 08:30:00",
        "domain": "dw.com",
        "language": "English",
        "sourcecountry": "DE",
    },
    {
        "url": "https://www.bbc.com/hindi/articles/c7060x65nd9o",
        "url_mobile": None,
        "title": "भारत-चीन सीमा पर क्या हुआ?",
        "seendate": "2025-06-15 19:45:00",
        "domain": "bbc.com",
        "language": "Hindi",
        "sourcecountry": "IN",
    },
    {
        "url": "https://www.chinadaily.com.cn/a/202212/17/WS639cff46a31057c47eba4d56.html",
        "url_mobile": None,
        "title": "China says India should not stir trouble on border",
        "seendate": "2025-06-15 10:20:00",
        "domain": "chinadaily.com.cn",
        "language": "English",
        "sourcecountry": "CN",
    },
    {
        "url": "https://www.lemonde.fr/international/article/2025/06/15/crise-otan-russie_6079514_3210.html",
        "url_mobile": None,
        "title": "Crise diplomatique entre l’OTAN et la Russie",
        "seendate": "2025-06-15 14:00:00",
        "domain": "lemonde.fr",
        "language": "French",
        "sourcecountry": "FR",
    },
    {
        "url": "https://elpais.com/ideas/2025-06-06/philip-kitcher-filosofo-la-vida-es-un-proyecto-humano-no-de-dios.html",
        "url_mobile": None,
        "title": 'Pol Morillas, politólogo: "Occidente ya no existe como referente"',
        "seendate": "2025-06-15 21:14:00",
        "domain": "elpais.com",
        "language": "Spanish",
        "sourcecountry": "ES",
    },
    {
        "url": "http://www.news.cn/world/20250614/853f06e4e32c4924b3fd09df5774b7e1/c.html",
        "url_mobile": None,
        "title": "中印边界问题特别代表会晤取得6点共识",
        "seendate": "2024-12-18T00:00:00",
        "socialimage": "",
        "domain": "xinhuanet.com",
        "language": "Chinese",
        "sourcecountry": "CN",
    },
]


mock_data_1 = {
    "articles": [
        {
            "url": "https://www.globaltimes.cn/page/202506/1336201.shtml",
            "title": "Straits Forum kicks off with over 7000 Taiwan participants",
            "seendate": "2025-06-15 21:14:00",
            "socialimage": "",
            "domain": "globaltimes.cn",
            "language": "Chinese",
            "sourcecountry": "CN",
        },
        {
            "url": "https://elpais.com/ideas/2025-06-16/pol-morillas-politologo-occidente-ya-no-existe-como-referente.html",
            "title": 'Pol Morillas, politólogo: "Occidente ya no existe como referente"',
            "seendate": "2025-06-16 10:00:00",
            "socialimage": "",
            "domain": "elpais.com",
            "language": "Spanish",
            "sourcecountry": "ES",
        },
        {
            "url": "https://english.kyodonews.net/news/2025/05/997a724fb51b-urgent-n-korea-fires-suspected-short-range-ballistic-missiles-s-korea-military.html",
            "title": "North Korea fires multiple ballistic missiles, no damage reported",
            "seendate": "2025-05-08 16:12:00",
            "socialimage": "",
            "domain": "english.kyodonews.net",
            "language": "English",
            "sourcecountry": "JP",
        },
        {
            "url": "https://www.dw.com/en/trump-signals-possible-us-involvement-in-iran-conflict/live-72913069",
            "title": "Trump signals 'possible' US involvement in Iran conflict",
            "seendate": "2025-06-15 00:00:00",
            "socialimage": "",
            "domain": "dw.com",
            "language": "English",
            "sourcecountry": "DE",
        },
        {
            "url": "https://www.alarabiya.net/iran",
            "title": "أهم وآخر أخبار إيران اليوم مباشرة",
            "seendate": "2025-06-15 12:00:00",
            "socialimage": "",
            "domain": "alarabiya.net",
            "language": "Arabic",
            "sourcecountry": "SA",
        },
        {
            "url": "https://elitards.com/international/2025/06/15/u-s-china-indo-pacific",
            "title": "U.S.–China Indo-Pacific tensions escalate",
            "seendate": "2025-06-15 09:00:00",
            "socialimage": "",
            "domain": "example.com",
            "language": "English",
            "sourcecountry": "US",
        },
        {
            "url": "https://elpais.com/america-colombia/2024-12-08/la-decada-sombria.html",
            "title": "La década sombría",
            "seendate": "2024-12-08 08:00:00",
            "socialimage": "",
            "domain": "elpais.com",
            "language": "Spanish",
            "sourcecountry": "CO",
        },
        {
            "url": "https://www.lemonde.fr/international/article/2025/06/15/crise-otan-russie_6079514_3210.html",
            "title": "Crise diplomatique entre l’OTAN et la Russie",
            "seendate": "2025-06-15 14:00:00",
            "socialimage": "",
            "domain": "lemonde.fr",
            "language": "French",
            "sourcecountry": "FR",
        },
    ],
    "query": "Multilingual Geopolitical Keywords",
    "maxrecords": 10,
    "totalArticles": 8,
    "status": "OK",
}
